script: |
  if [ ! -d "$HOME/app" ]; then
    git clone https://github.com/mohd-anas96/github-actions-demo.git $HOME/app
  fi

  cd $HOME/app

  git pull

  pip3 install --user -r requirements.txt

  pkill -f app.py || true

  nohup python3 app.py > output.log 2>&1 &
