name: CI/CD Deploy Flask App

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            if [ ! -d "$HOME/app" ]; then
              git clone https://github.com/mohd-anas96/github-actions-demo.git $HOME/app
            fi

            cd $HOME/app

            git pull

            pip3 install --user -r requirements.txt

            pkill -f app.py || true

            nohup python3 app.py > output.log 2>&1 &
